from .vqperceptual import VQLPIPSWithDiscriminator
from .vqperceptual_freq import VQLPIPSWithDiscriminator_wFreq
from .vqperceptual_wogan import VQLPIPS
from .lpips_freq import LPIPSWithFreq
from .contperceptual import LPIPSWithDiscriminator
from .contperceptual_wokl import LPIPSWithDiscriminator_woKL
